# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_susheel.ipynb.

# %% auto 0
__all__ = ['say_hello']

# %% ../00_susheel.ipynb 3
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
